# Generated by Django 2.1.7 on 2019-10-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
